SELECT A.TITLE,A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS,
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE LIKE '2022-10%'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;

-- 조인 조건이 보드테이블에 이너조인으로
--where year(A.CREATED_DATE) = '2022' AND MONTH(A.CREATED_DATE) = '10' 해도 됨
